[[redirects]]
  from = "/blog"
  to = "/news.html"
  status = 301

[[redirects]]
  from = "/blog/*"
  to = "/news.html?s=:splat"
  status = 301

[[redirects]]
  from = "/news"
  to = "/news.html"
  status = 301